---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hookshot.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "hookshot.labels" . | nindent 4 }}
  {{- with .Values.service.labels }}
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- with .Values.service }}
  {{- with .type }}
  type: {{ . }}
  {{- end }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- if .ports }}
  ports:
  {{- range $key, $value := .ports }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $key }}
      protocol: {{ $value.type }}
  {{- end }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "hookshot.selectorLabels" . | nindent 4 }}
